weather.api.key=84dd09ac77ffd820c9b90a5e661e62fe
aviation.api.key=e4425ee764b6af601acfcb41ec81bd1d
supabase.url=https://imixwdmkxaleinbqsega.supabase.co
supabase.anon.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImltaXh3ZG1reGFsZWluYnFzZWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQ2MDk3NDEsImV4cCI6MjA4MDE4NTc0MX0.neW-IGpq969BPD_rdqC3xm_kiBuEml-CqpPL3ddo_k0