# SimpleLogger configuration
org.slf4j.simpleLogger.defaultLogLevel=error
org.slf4j.simpleLogger.log.com.github.sarxos=error
org.slf4j.simpleLogger.log.org.opencv=error
org.slf4j.simpleLogger.log.org.bridj=error
org.slf4j.simpleLogger.showDateTime=true
org.slf4j.simpleLogger.dateTimeFormat=yyyy-MM-dd HH:mm:ss
org.slf4j.simpleLogger.showThreadName=false
org.slf4j.simpleLogger.showLogName=false
org.slf4j.simpleLogger.showShortLogName=true
# Suppress JavaFX internal warnings
org.slf4j.simpleLogger.log.com.sun.marlin=error
org.slf4j.simpleLogger.log.sun.misc=error